application: eclipse
version: 1
runtime: go
api_version: go1

handlers:
- url: /js
  static_dir: frontend/js

- url: /css
  static_dir: frontend/css

- url: /img
  static_dir: frontend/img

- url: /s/.*
  script: _go_app